server:
  port: 8080
spring:
  application:
    name:  trade-openapi
  ai:
    mcp:
      server:
        enabled: true # 启用/禁用 MCP 服务器 默认:true
        stdio: false # 启用/禁用 stdio 传输 默认:false
        name: trade-openapi
        version: 0.0.1
        type: SYNC
        sse-endpoint: /sse # 用于 Web 传输的自定义 SSE 终端节点路径 默认:/sse
        sse-message-endpoint: /mcp/message # 客户端用于发送消息的 Web 传输的自定义 SSE 消息终端节点路径 默认:/mcp/message
        tool-change-notification: true # 启用工具更改通知 默认:true
        request-timeout: 60
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
openapi:
  trade:
    default-channel: ibkr
    futu-default-env: 0 # 富途默认环境0:模拟 1:真实(用户配置项没有配置环境时用默认全局)
